project:
  type: website
  output-dir: docs

  
website:
  # title: "Kristjan Röx"
  site-url: https://www.kristjanrox.com
  description: "Röx website"
  favicon: "figures/rox_logo_transparent.png"
  draft-mode: gone
  
  page-footer: 
    left: "Copyright Kristjan Röx 2026. All rights reserved."
    border: true

  navbar:
    logo: "figures/rox_logo_transparent.png"
    background: dark 
    left:
      - href: index.qmd
        text: Articles
      - href: about.qmd
        text: About
    
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/kristjanrox/
      - icon: envelope
        href: mailto:kriorog@gmail.com
      - icon: rss
        href: index.xml
      
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    title-block-banner: true
    highlight-style: atom-one
    smooth-scroll: true
    html-math-method: mathjax

editor: visual

resources:
  - CNAME